/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.app

import com.example.utilities.StringUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    println(StringUtils.join(tokens))
}
