/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.app

import com.example.utilities.BarUtils
import javax.inject.Singleton

@Singleton
class MessageUtils(
    private val barUtils: BarUtils
) {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }

    fun foo() = "fooo!" + barUtils.bar()
}
