/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.app

import io.micronaut.runtime.Micronaut.*

fun main(args: Array<String>) {
    build()
        .args(*args)
        .packages("com.example")
        .start()
}
