micronaut:
  application:
    name: jooqTransaction
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'password'
    auto-commit: true

jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'